-- MySQL Script generated by MySQL Workbench
-- Sat Nov  30 12:13:17 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema eletros
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `eletros` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `eletros`;

DROP USER `sistemaweb`@`localhost`;
CREATE USER `sistemaweb`@`localhost` identified by "123456";
GRANT ALL PRIVILEGES ON eletros.* TO `sistemaweb`@`localhost`;
FLUSH PRIVILEGES;

-- -----------------------------------------------------
-- Table `eletros`.`equipamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eletros`.`equipamentos` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `potencia` DECIMAL(6,2) UNSIGNED,
  `quantidade` INT(10) UNSIGNED,
  `tempo` DECIMAL(5,2) UNSIGNED,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

--
-- Dumping data for table `registros`
--
INSERT INTO `equipamentos` (`id`, `nome`, `potencia`, `quantidade`, `tempo`, `created_at`, `updated_at`) VALUES (1, 'Lâmpada LED', 10, 10, 1, NOW(), NOW());
INSERT INTO `equipamentos` (`id`, `nome`, `potencia`, `quantidade`, `tempo`, `created_at`, `updated_at`) VALUES (2, 'Chuveiro', 4500, 1, 0.5, NOW(), NOW());
INSERT INTO `equipamentos` (`id`, `nome`, `potencia`, `quantidade`, `tempo`, `created_at`, `updated_at`) VALUES (3, 'Geladeira', 250, 1, 10, NOW(), NOW());
INSERT INTO `equipamentos` (`id`, `nome`, `potencia`, `quantidade`, `tempo`, `created_at`, `updated_at`) VALUES (4, 'Forno Microondas', 2000, 1, 0.1, NOW(), NOW());
INSERT INTO `equipamentos` (`id`, `nome`, `potencia`, `quantidade`, `tempo`, `created_at`, `updated_at`) VALUES (5, 'TV', 90, 2, 2, NOW(), NOW());
INSERT INTO `equipamentos` (`id`, `nome`, `potencia`, `quantidade`, `tempo`, `created_at`, `updated_at`) VALUES (6, 'Ferro de passar', 1000, 1, 0.2, NOW(), NOW());
INSERT INTO `equipamentos` (`id`, `nome`, `potencia`, `quantidade`, `tempo`, `created_at`, `updated_at`) VALUES (7, 'Ventilador', 100, 1, 4, NOW(), NOW());
INSERT INTO `equipamentos` (`id`, `nome`, `potencia`, `quantidade`, `tempo`, `created_at`, `updated_at`) VALUES (8, 'Lavadora de roupas', 1000, 1, 0.5, NOW(), NOW());


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
